name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        go:
          - "1"
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
        goexperiment: [""]
        include:
          # test with GOEXPERIMENT=loopvar
          # https://github.com/golang/go/wiki/LoopvarExperiment
          - os: ubuntu-latest
            go: "1.21"
            goexperiment: "loopvar"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/github.com/shogo82148/goa-v1
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go version
          echo "GO111MODULE=on" >> "$GITHUB_ENV"
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"
        shell: bash
      - run: make depend
        working-directory: src/github.com/shogo82148/goa-v1
      - run: make test
        working-directory: src/github.com/shogo82148/goa-v1
        env:
          GOEXPERIMENT: ${{ matrix.goexperiment }}
